name: "setup ovmlayer"
description: "setup ovmlayer on ubuntu-latest"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  rootfs:
    description: "rootfs tar"
    required: false
    default: "https://github.com/oomol/ovmlayer-rootfs/releases/download/base-rootfs%400.4.0/amd64-rootfs.tar"
  ref:
    description: "GitHub ref"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: download ovmlayer
      uses: actions/checkout@v4
      with:
        repository: oomol/ovmlayer
        path: ovmlayer
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - name: move ovmlayer to PATH
      run: |
        mv ovmlayer ../ovmlayer
        cd ../ovmlayer
        $(pwd)/build.sh $(uname -m)
        bin=$(find $(pwd) -name ovmlayer -type f)
        ln -sf $bin /usr/local/bin/ovmlayer
      shell: bash
    - name: setup ovmlayer environment
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends tar zstd
      shell: bash
    - name: download base rootfs
      run: |
        curl -L ${{inputs.rootfs}} -o base_rootfs.tar
      shell: bash
    - name: setup ovmlayer
      run: |
        sudo ovmlayer setup dev --base-rootfs=$(pwd)/base_rootfs.tar --layer-disk=/tmp/layer-disk
      shell: bash
