name: "setup oocana-node"
description: "setup oocana-node on ubuntu-latest"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  create-layer:
    description: "create layer"
    required: false
    default: "false"
  ref:
    description: "GitHub ref"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: oomol/oocana-node
        path: oocana-node
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - uses: pnpm/action-setup@v4
      with:
        package_json_file: oocana-node/package.json
    - uses: actions/setup-node@v4
      with:
        registry-url: https://npm.pkg.github.com/
        node-version: 22.x
        cache: pnpm
        cache-dependency-path: oocana-node/pnpm-lock.yaml
    - name: install
      run: pnpm install
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      shell: bash
      working-directory: oocana-node

    - name: build
      run: pnpm build
      shell: bash
      working-directory: oocana-node
    - name: create-layer
      if: ${{ inputs.create-layer != 'false' }}
      run: |
        node ./layer.mjs
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      working-directory: oocana-node
    # create-layer 的时候，会 install cli，提前换的话，cli 会被重置
    - name: replace oocana
      run: |
        cargo build
        cp target/debug/oocana oocana-node/packages/oocana/
        chmod +x oocana-node/packages/oocana/oocana
      shell: bash
    - name: test flow and other oocana api
      shell: bash
      run: pnpm run test
      working-directory: oocana-node
