name: Test on oocana-node
on:
  workflow_call:
    inputs:
      create-layer:
        required: false
        type: boolean
        default: false
      ovmlayer-repository:
        required: false
        type: string

jobs:
  test-node:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c
      options: --privileged --user 0:0
    defaults:
      run:
        shell: bash
    env:
      OVMLAYER_REPOSITORY: ${{ inputs.ovmlayer-repository || vars.OVMLAYER_REPOSITORY || 'ovmlayer-next' }}
      OVMLAYER_USE_RUNTIME_SETUP: ${{ (inputs.ovmlayer-repository || vars.OVMLAYER_REPOSITORY || 'ovmlayer-next') == (vars.OVMLAYER_REPOSITORY || 'ovmlayer-next') }}
    steps:
      - uses: actions/checkout@v6
        if: ${{ inputs.create-layer }}
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Generate GitHub App Token for oomol/${{ env.OVMLAYER_REPOSITORY }}
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OOMOL_DOWNLOADER_APP_ID }}
          private-key: ${{ secrets.OOMOL_DOWNLOADER_APP_PRIVATE_KEY }}
          owner: oomol
          repositories: ${{ env.OVMLAYER_REPOSITORY }}
        if: ${{ inputs.create-layer }}
      - uses: ./.github/actions/ovmlayer
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.OVMLAYER_REPOSITORY }}
          use-runtime-setup: ${{ env.OVMLAYER_USE_RUNTIME_SETUP }}
        if: ${{ inputs.create-layer }}
      - name: Download oocana
        uses: actions/download-artifact@v4
        with:
          name: oocana
          path: target
      - name: add permissions
        run: |
          chmod +x target/oocana
      - name: Install container dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends sudo
      - uses: oomol/oocana-node/.github/actions/oocana-node@main
        with:
          path: oocana-node
          create-layer: ${{ inputs.create-layer }}
          # ref: dev # uncomment this line to use a specific branch or tag
      - name: Start MQTT Broker
        run: |
          apt-get update && apt-get install -y --no-install-recommends mosquitto
          mosquitto -d -p 47688
      - name: replace oocana# cargo test will build the binary, so we only need to copy it
        run: cp target/oocana oocana-node/packages/oocana/
      - name: test flow and other oocana api
        run: pnpm run test
        working-directory: oocana-node
      - name: upload node logs
        uses: actions/upload-artifact@v4
        with:
          name: oocana-node-logs
          path: |
            ~/.oocana/sessions/
          retention-days: 1
        if: failure()
