name: Test on oocana-node
on:
  workflow_call:
    inputs:
      create-layer:
        required: false
        type: boolean
        default: false

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.create-layer }}
      - uses: ./.github/actions/ovmlayer
        with:
          token: ${{ secrets.ACCESS_REPO }}
        if: ${{ inputs.create-layer }}
      - name: Download oocana
        uses: actions/download-artifact@v4
        with:
          name: oocana
          path: target
      - name: add permissions
        run: |
          chmod +x target/oocana
      - uses: oomol/oocana-node/.github/actions/oocana-node@main
        with:
          path: oocana-node
          create-layer: ${{ inputs.create-layer }}
      - name: Start MQTT Broker
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends mosquitto
          mosquitto -d -p 47688
      - name: replace oocana# cargo test will build the binary, so we only need to copy it
        run: cp target/oocana oocana-node/packages/oocana/
      - name: test flow and other oocana api
        run: pnpm run test
        working-directory: oocana-node
      - name: upload node logs
        uses: actions/upload-artifact@v4
        with:
          name: oocana-node-logs
          path: |
            ~/.oocana/sessions/
          retention-days: 1
        if: failure()
