name: "ovmlayer action"
description: "setup ovmlayer on ubuntu-latest"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ovmlayer.yml"
      - ".github/actions/ovmlayer/action.yml"

jobs:
  ovmlayer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ovmlayer
        with:
          token: ${{ secrets.ACCESS_REPO }}